package ar.edu.unicen.exa.galvarez.patogis.servidor.modelo;

import java.io.Serializable;

public class Campana implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 8193740321757132712L;

	public Campana() {
		// TODO Auto-generated constructor stub
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column public.campana.id
	 * 
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column public.campana.nombre
	 * 
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	private String nombre;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column public.campana.id
	 * 
	 * @return the value of public.campana.id
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column public.campana.id
	 * 
	 * @param id
	 *            the value for public.campana.id
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column public.campana.nombre
	 * 
	 * @return the value of public.campana.nombre
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column public.campana.nombre
	 * 
	 * @param nombre
	 *            the value for public.campana.nombre
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
}