package ar.edu.unicen.exa.galvarez.patogis.servidor.modelo;

import java.io.Serializable;

public class Especie   implements Dominio, Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.especie.id
	 * @mbggenerated  Fri Aug 26 17:14:52 ART 2011
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.especie.nombre
	 * @mbggenerated  Fri Aug 26 17:14:52 ART 2011
	 */
	private String nombre;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.especie.nombre_cientifico
	 * @mbggenerated  Fri Aug 26 17:14:52 ART 2011
	 */
	private String nombreCientifico;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.especie.familia
	 * @mbggenerated  Fri Aug 26 17:14:52 ART 2011
	 */
	private String familia;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.especie.grupo
	 * @mbggenerated  Fri Aug 26 17:14:52 ART 2011
	 */
	private String grupo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.especie.id
	 * @return  the value of public.especie.id
	 * @mbggenerated  Fri Aug 26 17:14:52 ART 2011
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.especie.id
	 * @param id  the value for public.especie.id
	 * @mbggenerated  Fri Aug 26 17:14:52 ART 2011
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.especie.nombre
	 * @return  the value of public.especie.nombre
	 * @mbggenerated  Fri Aug 26 17:14:52 ART 2011
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.especie.nombre
	 * @param nombre  the value for public.especie.nombre
	 * @mbggenerated  Fri Aug 26 17:14:52 ART 2011
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.especie.nombre_cientifico
	 * @return  the value of public.especie.nombre_cientifico
	 * @mbggenerated  Fri Aug 26 17:14:52 ART 2011
	 */
	public String getNombreCientifico() {
		return nombreCientifico;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.especie.nombre_cientifico
	 * @param nombreCientifico  the value for public.especie.nombre_cientifico
	 * @mbggenerated  Fri Aug 26 17:14:52 ART 2011
	 */
	public void setNombreCientifico(String nombreCientifico) {
		this.nombreCientifico = nombreCientifico;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.especie.familia
	 * @return  the value of public.especie.familia
	 * @mbggenerated  Fri Aug 26 17:14:52 ART 2011
	 */
	public String getFamilia() {
		return familia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.especie.familia
	 * @param familia  the value for public.especie.familia
	 * @mbggenerated  Fri Aug 26 17:14:52 ART 2011
	 */
	public void setFamilia(String familia) {
		this.familia = familia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.especie.grupo
	 * @return  the value of public.especie.grupo
	 * @mbggenerated  Fri Aug 26 17:14:52 ART 2011
	 */
	public String getGrupo() {
		return grupo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.especie.grupo
	 * @param grupo  the value for public.especie.grupo
	 * @mbggenerated  Fri Aug 26 17:14:52 ART 2011
	 */
	public void setGrupo(String grupo) {
		this.grupo = grupo;
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = -8025097120999418899L;

	public Especie() {
		// TODO Auto-generated constructor stub
	}
	
	public void setCantidadObservaciones(Integer cantidadObservaciones) {
		this.cantidadObservaciones = cantidadObservaciones;
	}

	public Integer getCantidadObservaciones() {
		return cantidadObservaciones;
	}

	private Integer cantidadObservaciones;	
}