package ar.edu.unicen.exa.galvarez.patogis.servidor.modelo;

import java.io.Serializable;

public class ObservacionMatrizProductiva implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = -3117894425434173595L;

	public ObservacionMatrizProductiva() {
		// TODO Auto-generated constructor stub
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column public.observacion_matriz_productiva.id
	 * 
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column
	 * public.observacion_matriz_productiva.id_tipo_matriz_productiva
	 * 
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	private Integer idTipoMatrizProductiva;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column public.observacion_matriz_productiva.porcentaje
	 * 
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	private Integer porcentaje;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column public.observacion_matriz_productiva.id_observacion
	 * 
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	private Integer idObservacion;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column public.observacion_matriz_productiva.id
	 * 
	 * @return the value of public.observacion_matriz_productiva.id
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column public.observacion_matriz_productiva.id
	 * 
	 * @param id
	 *            the value for public.observacion_matriz_productiva.id
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column
	 * public.observacion_matriz_productiva.id_tipo_matriz_productiva
	 * 
	 * @return the value of
	 *         public.observacion_matriz_productiva.id_tipo_matriz_productiva
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public Integer getIdTipoMatrizProductiva() {
		return idTipoMatrizProductiva;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column
	 * public.observacion_matriz_productiva.id_tipo_matriz_productiva
	 * 
	 * @param idTipoMatrizProductiva
	 *            the value for public.observacion_matriz_productiva.
	 *            id_tipo_matriz_productiva
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public void setIdTipoMatrizProductiva(Integer idTipoMatrizProductiva) {
		this.idTipoMatrizProductiva = idTipoMatrizProductiva;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column
	 * public.observacion_matriz_productiva.porcentaje
	 * 
	 * @return the value of public.observacion_matriz_productiva.porcentaje
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public Integer getPorcentaje() {
		return porcentaje;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column
	 * public.observacion_matriz_productiva.porcentaje
	 * 
	 * @param porcentaje
	 *            the value for public.observacion_matriz_productiva.porcentaje
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public void setPorcentaje(Integer porcentaje) {
		this.porcentaje = porcentaje;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column
	 * public.observacion_matriz_productiva.id_observacion
	 * 
	 * @return the value of public.observacion_matriz_productiva.id_observacion
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public Integer getIdObservacion() {
		return idObservacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column
	 * public.observacion_matriz_productiva.id_observacion
	 * 
	 * @param idObservacion
	 *            the value for
	 *            public.observacion_matriz_productiva.id_observacion
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public void setIdObservacion(Integer idObservacion) {
		this.idObservacion = idObservacion;
	}
}