function aplicacionweb(){var O='',vb='" for "gwt:onLoadErrorFn"',tb='" for "gwt:onPropertyErrorFn"',hb='"><\/script>',Y='#',ic='.cache.html',$='/',Xb='09041A5040524F7B87C4CAC8E18E7BC5',Yb='2A80D7C94BFD31C705DA9099E0E428D3',Zb='4D6201BAB2448BBB2FA14EDC88226284',$b='77D04A82710A3A2BBE1F0E63442F129A',_b='88E1099AAC6489C040C06A73A559E83B',ac='9DCB6E754B1A612F950B23BD3CCB1FC4',hc=':',nb='::',qc='<script defer="defer">aplicacionweb.onInjectionDone(\'aplicacionweb\')<\/script>',gb='<script id="',qb='=',Z='?',bc='AABEAA3675B3DEFAF67D2E7CC27B54D5',cc='AF051F1F31A37B72CB5A7F2DEA15FB30',dc='BA5A19DECD9FEC23F38A6269E090ABC2',ec='BD63E2C24BDBDE11C5E0E7F2581DC215',fc='BFD120FAD1C26FD1503D993CCEBA4F48',sb='Bad handler "',pc='DOMContentLoaded',gc='E53581907FF3C64D9228C1FAF07C28A4',Eb='Gears.Factory',ib='SCRIPT',fb='__gwt_marker_aplicacionweb',P='aplicacionweb',db='aplicacionweb.nocache.js',mb='aplicacionweb::',Gb='application/x-googlegears',jb='base',bb='baseUrl',S='begin',R='bootstrap',ab='clear.cache.gif',pb='content',X='end',Bb='function',Db='gears',Rb='gecko',Sb='gecko1_8',Ab='geolocation.api',T='gwt.codesvr=',U='gwt.hosted=',V='gwt.hybrid',jc='gwt/standard/standard.css',ub='gwt:onLoadErrorFn',rb='gwt:onPropertyErrorFn',ob='gwt:property',oc='head',Vb='hosted.html?aplicacionweb',nc='href',Cb='html5',Qb='ie6',Pb='ie8',Ob='ie9',Fb='ie_mobile',wb='iframe',_='img',xb="javascript:''",kc='link',Ub='loadExternalRefs',kb='meta',zb='moduleRequested',W='moduleStartup',Nb='msie',lb='name',Ib='none',Hb='object',Kb='opera',yb='position:absolute;width:0;height:0;border:none',lc='rel',Mb='safari',cb='script',Wb='selectingPermutation',Q='startup',mc='stylesheet',eb='undefined',Tb='unknown',Jb='user.agent',Lb='webkit';var l=window,m=document,n=l.__gwtStatsEvent?function(a){return l.__gwtStatsEvent(a)}:null,o=l.__gwtStatsSessionId?l.__gwtStatsSessionId:null,p,q,r,s=O,t={},u=[],v=[],w=[],x=0,y,z;n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:R,millis:(new Date).getTime(),type:S});if(!l.__gwt_stylesLoaded){l.__gwt_stylesLoaded={}}if(!l.__gwt_scriptsLoaded){l.__gwt_scriptsLoaded={}}function A(){var b=false;try{var c=l.location.search;return (c.indexOf(T)!=-1||(c.indexOf(U)!=-1||l.external&&l.external.gwtOnLoad))&&c.indexOf(V)==-1}catch(a){}A=function(){return b};return b}
function B(){if(p&&q){var b=m.getElementById(P);var c=b.contentWindow;if(A()){c.__gwt_getProperty=function(a){return G(a)}}aplicacionweb=null;c.gwtOnLoad(y,P,s,x);n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:W,millis:(new Date).getTime(),type:X})}}
function C(){function e(a){var b=a.lastIndexOf(Y);if(b==-1){b=a.length}var c=a.indexOf(Z);if(c==-1){c=a.length}var d=a.lastIndexOf($,Math.min(c,b));return d>=0?a.substring(0,d+1):O}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=m.createElement(_);b.src=a+ab;a=e(b.src)}return a}
function g(){var a=E(bb);if(a!=null){return a}return O}
function h(){var a=m.getElementsByTagName(cb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(db)!=-1){return e(a[b].src)}}return O}
function i(){var a;if(typeof isBodyLoaded==eb||!isBodyLoaded()){var b=fb;var c;m.write(gb+b+hb);c=m.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=ib){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return O}
function j(){var a=m.getElementsByTagName(jb);if(a.length>0){return a[a.length-1].href}return O}
var k=g();if(k==O){k=h()}if(k==O){k=i()}if(k==O){k=j()}if(k==O){k=e(m.location.href)}k=f(k);s=k;return k}
function D(){var b=document.getElementsByTagName(kb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(lb),g;if(f){f=f.replace(mb,O);if(f.indexOf(nb)>=0){continue}if(f==ob){g=e.getAttribute(pb);if(g){var h,i=g.indexOf(qb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=O}t[f]=h}}else if(f==rb){g=e.getAttribute(pb);if(g){try{z=eval(g)}catch(a){alert(sb+g+tb)}}}else if(f==ub){g=e.getAttribute(pb);if(g){try{y=eval(g)}catch(a){alert(sb+g+vb)}}}}}}
function E(a){var b=t[a];return b==null?null:b}
function F(a,b){var c=w;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function G(a){var b=v[a](),c=u[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(z){z(a,d,b)}throw null}
var H;function I(){if(!H){H=true;var a=m.createElement(wb);a.src=xb;a.id=P;a.style.cssText=yb;a.tabIndex=-1;m.body.appendChild(a);n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:W,millis:(new Date).getTime(),type:zb});a.contentWindow.location.replace(s+K)}}
v[Ab]=function(){if(typeof navigator.geolocation!=eb&&typeof navigator.geolocation.getCurrentPosition==Bb){return Cb}if(window.google&&google.gears){return Db}var b=null;if(typeof GearsFactory!=eb){b=new GearsFactory}else{try{b=new ActiveXObject(Eb);if(b.getBuildInfo().indexOf(Fb)!=-1){b.privateSetGlobalObject(this)}}catch(a){if(typeof navigator.mimeTypes!=eb&&navigator.mimeTypes[Gb]){b=document.createElement(Hb);b.style.display=Ib;b.width=0;b.height=0;b.type=Gb;document.documentElement.appendChild(b)}}}if(!b){return Cb}if(!window.google){google={}}if(!google.gears){google.gears={factory:b}}return Db};u[Ab]={gears:0,html5:1};v[Jb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Kb)!=-1}())return Kb;if(function(){return b.indexOf(Lb)!=-1}())return Mb;if(function(){return b.indexOf(Nb)!=-1&&m.documentMode>=9}())return Ob;if(function(){return b.indexOf(Nb)!=-1&&m.documentMode>=8}())return Pb;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return Qb;if(function(){return b.indexOf(Rb)!=-1}())return Sb;return Tb};u[Jb]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};aplicacionweb.onScriptLoad=function(){if(H){q=true;B()}};aplicacionweb.onInjectionDone=function(){p=true;n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:Ub,millis:(new Date).getTime(),type:X});B()};D();C();var J;var K;if(A()){if(l.external&&(l.external.initModule&&l.external.initModule(P))){l.location.reload();return}K=Vb;J=O}n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:R,millis:(new Date).getTime(),type:Wb});if(!A()){try{F([Db,Pb],Xb);F([Cb,Kb],Yb);F([Db,Kb],Zb);F([Cb,Mb],$b);F([Db,Ob],_b);F([Db,Qb],ac);F([Cb,Pb],bc);F([Db,Sb],cc);F([Cb,Sb],dc);F([Cb,Ob],ec);F([Cb,Qb],fc);F([Db,Mb],gc);J=w[G(Ab)][G(Jb)];var L=J.indexOf(hc);if(L!=-1){x=Number(J.substring(L+1));J=J.substring(0,L)}K=J+ic}catch(a){return}}var M;function N(){if(!r){r=true;if(!__gwt_stylesLoaded[jc]){var a=m.createElement(kc);__gwt_stylesLoaded[jc]=a;a.setAttribute(lc,mc);a.setAttribute(nc,s+jc);m.getElementsByTagName(oc)[0].appendChild(a)}B();if(m.removeEventListener){m.removeEventListener(pc,N,false)}if(M){clearInterval(M)}}}
if(m.addEventListener){m.addEventListener(pc,function(){I();N()},false)}var M=setInterval(function(){if(/loaded|complete/.test(m.readyState)){I();N()}},50);n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:R,millis:(new Date).getTime(),type:X});n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:Ub,millis:(new Date).getTime(),type:S});m.write(qc)}
aplicacionweb();