package ar.edu.unicen.exa.galvarez.patogis.servidor.logica;

import ar.edu.unicen.exa.galvarez.patogis.servidor.modelo.ObservacionClima;
import ar.edu.unicen.exa.galvarez.patogis.servidor.modelo.ObservacionClimaExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ObservacionClimaMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_clima
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int countByExample(ObservacionClimaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_clima
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int deleteByExample(ObservacionClimaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_clima
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_clima
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int insert(ObservacionClima record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_clima
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int insertSelective(ObservacionClima record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_clima
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	List<ObservacionClima> selectByExample(ObservacionClimaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_clima
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	ObservacionClima selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_clima
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int updateByExampleSelective(@Param("record") ObservacionClima record,
			@Param("example") ObservacionClimaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_clima
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int updateByExample(@Param("record") ObservacionClima record,
			@Param("example") ObservacionClimaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_clima
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int updateByPrimaryKeySelective(ObservacionClima record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_clima
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int updateByPrimaryKey(ObservacionClima record);
}