package ar.edu.unicen.exa.galvarez.patogis.servidor.logica;

import ar.edu.unicen.exa.galvarez.patogis.servidor.modelo.ObservacionFoto;
import ar.edu.unicen.exa.galvarez.patogis.servidor.modelo.ObservacionFotoExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ObservacionFotoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_foto
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int countByExample(ObservacionFotoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_foto
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int deleteByExample(ObservacionFotoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_foto
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int insert(ObservacionFoto record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_foto
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int insertSelective(ObservacionFoto record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_foto
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	List<ObservacionFoto> selectByExample(ObservacionFotoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_foto
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int updateByExampleSelective(@Param("record") ObservacionFoto record,
			@Param("example") ObservacionFotoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_foto
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int updateByExample(@Param("record") ObservacionFoto record,
			@Param("example") ObservacionFotoExample example);
}