package ar.edu.unicen.exa.galvarez.patogis.servidor.logica;

import ar.edu.unicen.exa.galvarez.patogis.servidor.modelo.Observacion;
import ar.edu.unicen.exa.galvarez.patogis.servidor.modelo.ObservacionExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ObservacionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int countByExample(ObservacionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int deleteByExample(ObservacionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int insert(Observacion record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int insertSelective(Observacion record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	List<Observacion> selectByExample(ObservacionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	Observacion selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int updateByExampleSelective(@Param("record") Observacion record,
			@Param("example") ObservacionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int updateByExample(@Param("record") Observacion record,
			@Param("example") ObservacionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int updateByPrimaryKeySelective(Observacion record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int updateByPrimaryKey(Observacion record);
}