package ar.edu.unicen.exa.galvarez.patogis.servidor.logica;

import ar.edu.unicen.exa.galvarez.patogis.servidor.modelo.ObservacionEspecie;
import ar.edu.unicen.exa.galvarez.patogis.servidor.modelo.ObservacionEspecieExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ObservacionEspecieMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_especie
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int countByExample(ObservacionEspecieExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_especie
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int deleteByExample(ObservacionEspecieExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_especie
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_especie
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int insert(ObservacionEspecie record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_especie
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int insertSelective(ObservacionEspecie record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_especie
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	List<ObservacionEspecie> selectByExample(ObservacionEspecieExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_especie
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	ObservacionEspecie selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_especie
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int updateByExampleSelective(@Param("record") ObservacionEspecie record,
			@Param("example") ObservacionEspecieExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_especie
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int updateByExample(@Param("record") ObservacionEspecie record,
			@Param("example") ObservacionEspecieExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_especie
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int updateByPrimaryKeySelective(ObservacionEspecie record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_especie
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int updateByPrimaryKey(ObservacionEspecie record);
}