package ar.edu.unicen.exa.galvarez.patogis.servidor.logica;

import ar.edu.unicen.exa.galvarez.patogis.servidor.modelo.ObservacionMatrizProductiva;
import ar.edu.unicen.exa.galvarez.patogis.servidor.modelo.ObservacionMatrizProductivaExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ObservacionMatrizProductivaMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_matriz_productiva
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int countByExample(ObservacionMatrizProductivaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_matriz_productiva
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int deleteByExample(ObservacionMatrizProductivaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_matriz_productiva
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_matriz_productiva
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int insert(ObservacionMatrizProductiva record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_matriz_productiva
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int insertSelective(ObservacionMatrizProductiva record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_matriz_productiva
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	List<ObservacionMatrizProductiva> selectByExample(
			ObservacionMatrizProductivaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_matriz_productiva
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	ObservacionMatrizProductiva selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_matriz_productiva
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int updateByExampleSelective(
			@Param("record") ObservacionMatrizProductiva record,
			@Param("example") ObservacionMatrizProductivaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_matriz_productiva
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int updateByExample(@Param("record") ObservacionMatrizProductiva record,
			@Param("example") ObservacionMatrizProductivaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_matriz_productiva
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int updateByPrimaryKeySelective(ObservacionMatrizProductiva record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_matriz_productiva
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int updateByPrimaryKey(ObservacionMatrizProductiva record);
}