package ar.edu.unicen.exa.galvarez.patogis.servidor.logica;

import ar.edu.unicen.exa.galvarez.patogis.servidor.modelo.ParUsuarios;
import ar.edu.unicen.exa.galvarez.patogis.servidor.modelo.ParUsuariosExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ParUsuariosMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.par_usuarios
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int countByExample(ParUsuariosExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.par_usuarios
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int deleteByExample(ParUsuariosExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.par_usuarios
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.par_usuarios
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int insert(ParUsuarios record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.par_usuarios
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int insertSelective(ParUsuarios record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.par_usuarios
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	List<ParUsuarios> selectByExample(ParUsuariosExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.par_usuarios
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	ParUsuarios selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.par_usuarios
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int updateByExampleSelective(@Param("record") ParUsuarios record,
			@Param("example") ParUsuariosExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.par_usuarios
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int updateByExample(@Param("record") ParUsuarios record,
			@Param("example") ParUsuariosExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.par_usuarios
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int updateByPrimaryKeySelective(ParUsuarios record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.par_usuarios
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int updateByPrimaryKey(ParUsuarios record);
}