package ar.edu.unicen.exa.galvarez.patogis.servidor.logica;

import ar.edu.unicen.exa.galvarez.patogis.servidor.modelo.TipoMatrizProductiva;
import ar.edu.unicen.exa.galvarez.patogis.servidor.modelo.TipoMatrizProductivaExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TipoMatrizProductivaMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tipo_matriz_productiva
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int countByExample(TipoMatrizProductivaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tipo_matriz_productiva
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int deleteByExample(TipoMatrizProductivaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tipo_matriz_productiva
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tipo_matriz_productiva
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int insert(TipoMatrizProductiva record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tipo_matriz_productiva
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int insertSelective(TipoMatrizProductiva record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tipo_matriz_productiva
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	List<TipoMatrizProductiva> selectByExample(
			TipoMatrizProductivaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tipo_matriz_productiva
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	TipoMatrizProductiva selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tipo_matriz_productiva
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int updateByExampleSelective(@Param("record") TipoMatrizProductiva record,
			@Param("example") TipoMatrizProductivaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tipo_matriz_productiva
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int updateByExample(@Param("record") TipoMatrizProductiva record,
			@Param("example") TipoMatrizProductivaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tipo_matriz_productiva
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int updateByPrimaryKeySelective(TipoMatrizProductiva record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tipo_matriz_productiva
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int updateByPrimaryKey(TipoMatrizProductiva record);
}