package ar.edu.unicen.exa.galvarez.patogis.servidor.logica;

import ar.edu.unicen.exa.galvarez.patogis.servidor.modelo.Usuario;
import ar.edu.unicen.exa.galvarez.patogis.servidor.modelo.UsuarioExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsuarioMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.usuario
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int countByExample(UsuarioExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.usuario
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int deleteByExample(UsuarioExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.usuario
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.usuario
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int insert(Usuario record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.usuario
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int insertSelective(Usuario record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.usuario
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	List<Usuario> selectByExample(UsuarioExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.usuario
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	Usuario selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.usuario
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int updateByExampleSelective(@Param("record") Usuario record,
			@Param("example") UsuarioExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.usuario
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int updateByExample(@Param("record") Usuario record,
			@Param("example") UsuarioExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.usuario
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int updateByPrimaryKeySelective(Usuario record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.usuario
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	int updateByPrimaryKey(Usuario record);
}