package ar.edu.unicen.exa.galvarez.patogis.servidor.modelo;

public class Especie {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.especie.id
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.especie.nombre
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	private String nombre;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.especie.id
	 * @return  the value of public.especie.id
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.especie.id
	 * @param id  the value for public.especie.id
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.especie.nombre
	 * @return  the value of public.especie.nombre
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.especie.nombre
	 * @param nombre  the value for public.especie.nombre
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
}