package ar.edu.unicen.exa.galvarez.patogis.servidor.modelo;

import java.util.ArrayList;
import java.util.List;

public class EspecieExample {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.especie
	 * @mbggenerated  Tue Oct 25 20:22:19 ART 2011
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.especie
	 * @mbggenerated  Tue Oct 25 20:22:19 ART 2011
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.especie
	 * @mbggenerated  Tue Oct 25 20:22:19 ART 2011
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.especie
	 * @mbggenerated  Tue Oct 25 20:22:19 ART 2011
	 */
	public EspecieExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.especie
	 * @mbggenerated  Tue Oct 25 20:22:19 ART 2011
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.especie
	 * @mbggenerated  Tue Oct 25 20:22:19 ART 2011
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.especie
	 * @mbggenerated  Tue Oct 25 20:22:19 ART 2011
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.especie
	 * @mbggenerated  Tue Oct 25 20:22:19 ART 2011
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.especie
	 * @mbggenerated  Tue Oct 25 20:22:19 ART 2011
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.especie
	 * @mbggenerated  Tue Oct 25 20:22:19 ART 2011
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.especie
	 * @mbggenerated  Tue Oct 25 20:22:19 ART 2011
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.especie
	 * @mbggenerated  Tue Oct 25 20:22:19 ART 2011
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.especie
	 * @mbggenerated  Tue Oct 25 20:22:19 ART 2011
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.especie
	 * @mbggenerated  Tue Oct 25 20:22:19 ART 2011
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table public.especie
	 * @mbggenerated  Tue Oct 25 20:22:19 ART 2011
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andNombreIsNull() {
			addCriterion("nombre is null");
			return (Criteria) this;
		}

		public Criteria andNombreIsNotNull() {
			addCriterion("nombre is not null");
			return (Criteria) this;
		}

		public Criteria andNombreEqualTo(String value) {
			addCriterion("nombre =", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreNotEqualTo(String value) {
			addCriterion("nombre <>", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreGreaterThan(String value) {
			addCriterion("nombre >", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreGreaterThanOrEqualTo(String value) {
			addCriterion("nombre >=", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreLessThan(String value) {
			addCriterion("nombre <", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreLessThanOrEqualTo(String value) {
			addCriterion("nombre <=", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreLike(String value) {
			addCriterion("nombre like", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreNotLike(String value) {
			addCriterion("nombre not like", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreIn(List<String> values) {
			addCriterion("nombre in", values, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreNotIn(List<String> values) {
			addCriterion("nombre not in", values, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreBetween(String value1, String value2) {
			addCriterion("nombre between", value1, value2, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreNotBetween(String value1, String value2) {
			addCriterion("nombre not between", value1, value2, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreCientificoIsNull() {
			addCriterion("nombre_cientifico is null");
			return (Criteria) this;
		}

		public Criteria andNombreCientificoIsNotNull() {
			addCriterion("nombre_cientifico is not null");
			return (Criteria) this;
		}

		public Criteria andNombreCientificoEqualTo(String value) {
			addCriterion("nombre_cientifico =", value, "nombreCientifico");
			return (Criteria) this;
		}

		public Criteria andNombreCientificoNotEqualTo(String value) {
			addCriterion("nombre_cientifico <>", value, "nombreCientifico");
			return (Criteria) this;
		}

		public Criteria andNombreCientificoGreaterThan(String value) {
			addCriterion("nombre_cientifico >", value, "nombreCientifico");
			return (Criteria) this;
		}

		public Criteria andNombreCientificoGreaterThanOrEqualTo(String value) {
			addCriterion("nombre_cientifico >=", value, "nombreCientifico");
			return (Criteria) this;
		}

		public Criteria andNombreCientificoLessThan(String value) {
			addCriterion("nombre_cientifico <", value, "nombreCientifico");
			return (Criteria) this;
		}

		public Criteria andNombreCientificoLessThanOrEqualTo(String value) {
			addCriterion("nombre_cientifico <=", value, "nombreCientifico");
			return (Criteria) this;
		}

		public Criteria andNombreCientificoLike(String value) {
			addCriterion("nombre_cientifico like", value, "nombreCientifico");
			return (Criteria) this;
		}

		public Criteria andNombreCientificoNotLike(String value) {
			addCriterion("nombre_cientifico not like", value,
					"nombreCientifico");
			return (Criteria) this;
		}

		public Criteria andNombreCientificoIn(List<String> values) {
			addCriterion("nombre_cientifico in", values, "nombreCientifico");
			return (Criteria) this;
		}

		public Criteria andNombreCientificoNotIn(List<String> values) {
			addCriterion("nombre_cientifico not in", values, "nombreCientifico");
			return (Criteria) this;
		}

		public Criteria andNombreCientificoBetween(String value1, String value2) {
			addCriterion("nombre_cientifico between", value1, value2,
					"nombreCientifico");
			return (Criteria) this;
		}

		public Criteria andNombreCientificoNotBetween(String value1,
				String value2) {
			addCriterion("nombre_cientifico not between", value1, value2,
					"nombreCientifico");
			return (Criteria) this;
		}

		public Criteria andFamiliaIsNull() {
			addCriterion("familia is null");
			return (Criteria) this;
		}

		public Criteria andFamiliaIsNotNull() {
			addCriterion("familia is not null");
			return (Criteria) this;
		}

		public Criteria andFamiliaEqualTo(String value) {
			addCriterion("familia =", value, "familia");
			return (Criteria) this;
		}

		public Criteria andFamiliaNotEqualTo(String value) {
			addCriterion("familia <>", value, "familia");
			return (Criteria) this;
		}

		public Criteria andFamiliaGreaterThan(String value) {
			addCriterion("familia >", value, "familia");
			return (Criteria) this;
		}

		public Criteria andFamiliaGreaterThanOrEqualTo(String value) {
			addCriterion("familia >=", value, "familia");
			return (Criteria) this;
		}

		public Criteria andFamiliaLessThan(String value) {
			addCriterion("familia <", value, "familia");
			return (Criteria) this;
		}

		public Criteria andFamiliaLessThanOrEqualTo(String value) {
			addCriterion("familia <=", value, "familia");
			return (Criteria) this;
		}

		public Criteria andFamiliaLike(String value) {
			addCriterion("familia like", value, "familia");
			return (Criteria) this;
		}

		public Criteria andFamiliaNotLike(String value) {
			addCriterion("familia not like", value, "familia");
			return (Criteria) this;
		}

		public Criteria andFamiliaIn(List<String> values) {
			addCriterion("familia in", values, "familia");
			return (Criteria) this;
		}

		public Criteria andFamiliaNotIn(List<String> values) {
			addCriterion("familia not in", values, "familia");
			return (Criteria) this;
		}

		public Criteria andFamiliaBetween(String value1, String value2) {
			addCriterion("familia between", value1, value2, "familia");
			return (Criteria) this;
		}

		public Criteria andFamiliaNotBetween(String value1, String value2) {
			addCriterion("familia not between", value1, value2, "familia");
			return (Criteria) this;
		}

		public Criteria andGrupoIsNull() {
			addCriterion("grupo is null");
			return (Criteria) this;
		}

		public Criteria andGrupoIsNotNull() {
			addCriterion("grupo is not null");
			return (Criteria) this;
		}

		public Criteria andGrupoEqualTo(String value) {
			addCriterion("grupo =", value, "grupo");
			return (Criteria) this;
		}

		public Criteria andGrupoNotEqualTo(String value) {
			addCriterion("grupo <>", value, "grupo");
			return (Criteria) this;
		}

		public Criteria andGrupoGreaterThan(String value) {
			addCriterion("grupo >", value, "grupo");
			return (Criteria) this;
		}

		public Criteria andGrupoGreaterThanOrEqualTo(String value) {
			addCriterion("grupo >=", value, "grupo");
			return (Criteria) this;
		}

		public Criteria andGrupoLessThan(String value) {
			addCriterion("grupo <", value, "grupo");
			return (Criteria) this;
		}

		public Criteria andGrupoLessThanOrEqualTo(String value) {
			addCriterion("grupo <=", value, "grupo");
			return (Criteria) this;
		}

		public Criteria andGrupoLike(String value) {
			addCriterion("grupo like", value, "grupo");
			return (Criteria) this;
		}

		public Criteria andGrupoNotLike(String value) {
			addCriterion("grupo not like", value, "grupo");
			return (Criteria) this;
		}

		public Criteria andGrupoIn(List<String> values) {
			addCriterion("grupo in", values, "grupo");
			return (Criteria) this;
		}

		public Criteria andGrupoNotIn(List<String> values) {
			addCriterion("grupo not in", values, "grupo");
			return (Criteria) this;
		}

		public Criteria andGrupoBetween(String value1, String value2) {
			addCriterion("grupo between", value1, value2, "grupo");
			return (Criteria) this;
		}

		public Criteria andGrupoNotBetween(String value1, String value2) {
			addCriterion("grupo not between", value1, value2, "grupo");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table public.especie
	 * @mbggenerated  Tue Oct 25 20:22:19 ART 2011
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table especie
	 * 
	 * @mbggenerated do_not_delete_during_merge Sat Jun 04 08:05:19 ART 2011
	 */
	public static class Criteria extends GeneratedCriteria {

		protected Criteria() {
			super();
		}
	}
}