package ar.edu.unicen.exa.galvarez.patogis.servidor.modelo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ObservacionExample {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table public.observacion
	 * 
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table public.observacion
	 * 
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table public.observacion
	 * 
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.observacion
	 * 
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public ObservacionExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.observacion
	 * 
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.observacion
	 * 
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.observacion
	 * 
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.observacion
	 * 
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.observacion
	 * 
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.observacion
	 * 
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.observacion
	 * 
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.observacion
	 * 
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.observacion
	 * 
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.observacion
	 * 
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table public.observacion
	 * 
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andInicioIsNull() {
			addCriterion("inicio is null");
			return (Criteria) this;
		}

		public Criteria andInicioIsNotNull() {
			addCriterion("inicio is not null");
			return (Criteria) this;
		}

		public Criteria andInicioEqualTo(Date value) {
			addCriterion("inicio =", value, "inicio");
			return (Criteria) this;
		}

		public Criteria andInicioNotEqualTo(Date value) {
			addCriterion("inicio <>", value, "inicio");
			return (Criteria) this;
		}

		public Criteria andInicioGreaterThan(Date value) {
			addCriterion("inicio >", value, "inicio");
			return (Criteria) this;
		}

		public Criteria andInicioGreaterThanOrEqualTo(Date value) {
			addCriterion("inicio >=", value, "inicio");
			return (Criteria) this;
		}

		public Criteria andInicioLessThan(Date value) {
			addCriterion("inicio <", value, "inicio");
			return (Criteria) this;
		}

		public Criteria andInicioLessThanOrEqualTo(Date value) {
			addCriterion("inicio <=", value, "inicio");
			return (Criteria) this;
		}

		public Criteria andInicioIn(List<Date> values) {
			addCriterion("inicio in", values, "inicio");
			return (Criteria) this;
		}

		public Criteria andInicioNotIn(List<Date> values) {
			addCriterion("inicio not in", values, "inicio");
			return (Criteria) this;
		}

		public Criteria andInicioBetween(Date value1, Date value2) {
			addCriterion("inicio between", value1, value2, "inicio");
			return (Criteria) this;
		}

		public Criteria andInicioNotBetween(Date value1, Date value2) {
			addCriterion("inicio not between", value1, value2, "inicio");
			return (Criteria) this;
		}

		public Criteria andFinIsNull() {
			addCriterion("fin is null");
			return (Criteria) this;
		}

		public Criteria andFinIsNotNull() {
			addCriterion("fin is not null");
			return (Criteria) this;
		}

		public Criteria andFinEqualTo(Date value) {
			addCriterion("fin =", value, "fin");
			return (Criteria) this;
		}

		public Criteria andFinNotEqualTo(Date value) {
			addCriterion("fin <>", value, "fin");
			return (Criteria) this;
		}

		public Criteria andFinGreaterThan(Date value) {
			addCriterion("fin >", value, "fin");
			return (Criteria) this;
		}

		public Criteria andFinGreaterThanOrEqualTo(Date value) {
			addCriterion("fin >=", value, "fin");
			return (Criteria) this;
		}

		public Criteria andFinLessThan(Date value) {
			addCriterion("fin <", value, "fin");
			return (Criteria) this;
		}

		public Criteria andFinLessThanOrEqualTo(Date value) {
			addCriterion("fin <=", value, "fin");
			return (Criteria) this;
		}

		public Criteria andFinIn(List<Date> values) {
			addCriterion("fin in", values, "fin");
			return (Criteria) this;
		}

		public Criteria andFinNotIn(List<Date> values) {
			addCriterion("fin not in", values, "fin");
			return (Criteria) this;
		}

		public Criteria andFinBetween(Date value1, Date value2) {
			addCriterion("fin between", value1, value2, "fin");
			return (Criteria) this;
		}

		public Criteria andFinNotBetween(Date value1, Date value2) {
			addCriterion("fin not between", value1, value2, "fin");
			return (Criteria) this;
		}

		public Criteria andAlcanceIsNull() {
			addCriterion("alcance is null");
			return (Criteria) this;
		}

		public Criteria andAlcanceIsNotNull() {
			addCriterion("alcance is not null");
			return (Criteria) this;
		}

		public Criteria andAlcanceEqualTo(String value) {
			addCriterion("alcance =", value, "alcance");
			return (Criteria) this;
		}

		public Criteria andAlcanceNotEqualTo(String value) {
			addCriterion("alcance <>", value, "alcance");
			return (Criteria) this;
		}

		public Criteria andAlcanceGreaterThan(String value) {
			addCriterion("alcance >", value, "alcance");
			return (Criteria) this;
		}

		public Criteria andAlcanceGreaterThanOrEqualTo(String value) {
			addCriterion("alcance >=", value, "alcance");
			return (Criteria) this;
		}

		public Criteria andAlcanceLessThan(String value) {
			addCriterion("alcance <", value, "alcance");
			return (Criteria) this;
		}

		public Criteria andAlcanceLessThanOrEqualTo(String value) {
			addCriterion("alcance <=", value, "alcance");
			return (Criteria) this;
		}

		public Criteria andAlcanceLike(String value) {
			addCriterion("alcance like", value, "alcance");
			return (Criteria) this;
		}

		public Criteria andAlcanceNotLike(String value) {
			addCriterion("alcance not like", value, "alcance");
			return (Criteria) this;
		}

		public Criteria andAlcanceIn(List<String> values) {
			addCriterion("alcance in", values, "alcance");
			return (Criteria) this;
		}

		public Criteria andAlcanceNotIn(List<String> values) {
			addCriterion("alcance not in", values, "alcance");
			return (Criteria) this;
		}

		public Criteria andAlcanceBetween(String value1, String value2) {
			addCriterion("alcance between", value1, value2, "alcance");
			return (Criteria) this;
		}

		public Criteria andAlcanceNotBetween(String value1, String value2) {
			addCriterion("alcance not between", value1, value2, "alcance");
			return (Criteria) this;
		}

		public Criteria andObservacionesIsNull() {
			addCriterion("observaciones is null");
			return (Criteria) this;
		}

		public Criteria andObservacionesIsNotNull() {
			addCriterion("observaciones is not null");
			return (Criteria) this;
		}

		public Criteria andObservacionesEqualTo(String value) {
			addCriterion("observaciones =", value, "observaciones");
			return (Criteria) this;
		}

		public Criteria andObservacionesNotEqualTo(String value) {
			addCriterion("observaciones <>", value, "observaciones");
			return (Criteria) this;
		}

		public Criteria andObservacionesGreaterThan(String value) {
			addCriterion("observaciones >", value, "observaciones");
			return (Criteria) this;
		}

		public Criteria andObservacionesGreaterThanOrEqualTo(String value) {
			addCriterion("observaciones >=", value, "observaciones");
			return (Criteria) this;
		}

		public Criteria andObservacionesLessThan(String value) {
			addCriterion("observaciones <", value, "observaciones");
			return (Criteria) this;
		}

		public Criteria andObservacionesLessThanOrEqualTo(String value) {
			addCriterion("observaciones <=", value, "observaciones");
			return (Criteria) this;
		}

		public Criteria andObservacionesLike(String value) {
			addCriterion("observaciones like", value, "observaciones");
			return (Criteria) this;
		}

		public Criteria andObservacionesNotLike(String value) {
			addCriterion("observaciones not like", value, "observaciones");
			return (Criteria) this;
		}

		public Criteria andObservacionesIn(List<String> values) {
			addCriterion("observaciones in", values, "observaciones");
			return (Criteria) this;
		}

		public Criteria andObservacionesNotIn(List<String> values) {
			addCriterion("observaciones not in", values, "observaciones");
			return (Criteria) this;
		}

		public Criteria andObservacionesBetween(String value1, String value2) {
			addCriterion("observaciones between", value1, value2,
					"observaciones");
			return (Criteria) this;
		}

		public Criteria andObservacionesNotBetween(String value1, String value2) {
			addCriterion("observaciones not between", value1, value2,
					"observaciones");
			return (Criteria) this;
		}

		public Criteria andIdUbicacionIsNull() {
			addCriterion("id_ubicacion is null");
			return (Criteria) this;
		}

		public Criteria andIdUbicacionIsNotNull() {
			addCriterion("id_ubicacion is not null");
			return (Criteria) this;
		}

		public Criteria andIdUbicacionEqualTo(Integer value) {
			addCriterion("id_ubicacion =", value, "idUbicacion");
			return (Criteria) this;
		}

		public Criteria andIdUbicacionNotEqualTo(Integer value) {
			addCriterion("id_ubicacion <>", value, "idUbicacion");
			return (Criteria) this;
		}

		public Criteria andIdUbicacionGreaterThan(Integer value) {
			addCriterion("id_ubicacion >", value, "idUbicacion");
			return (Criteria) this;
		}

		public Criteria andIdUbicacionGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_ubicacion >=", value, "idUbicacion");
			return (Criteria) this;
		}

		public Criteria andIdUbicacionLessThan(Integer value) {
			addCriterion("id_ubicacion <", value, "idUbicacion");
			return (Criteria) this;
		}

		public Criteria andIdUbicacionLessThanOrEqualTo(Integer value) {
			addCriterion("id_ubicacion <=", value, "idUbicacion");
			return (Criteria) this;
		}

		public Criteria andIdUbicacionIn(List<Integer> values) {
			addCriterion("id_ubicacion in", values, "idUbicacion");
			return (Criteria) this;
		}

		public Criteria andIdUbicacionNotIn(List<Integer> values) {
			addCriterion("id_ubicacion not in", values, "idUbicacion");
			return (Criteria) this;
		}

		public Criteria andIdUbicacionBetween(Integer value1, Integer value2) {
			addCriterion("id_ubicacion between", value1, value2, "idUbicacion");
			return (Criteria) this;
		}

		public Criteria andIdUbicacionNotBetween(Integer value1, Integer value2) {
			addCriterion("id_ubicacion not between", value1, value2,
					"idUbicacion");
			return (Criteria) this;
		}

		public Criteria andIdCampanaIsNull() {
			addCriterion("id_campana is null");
			return (Criteria) this;
		}

		public Criteria andIdCampanaIsNotNull() {
			addCriterion("id_campana is not null");
			return (Criteria) this;
		}

		public Criteria andIdCampanaEqualTo(Integer value) {
			addCriterion("id_campana =", value, "idCampana");
			return (Criteria) this;
		}

		public Criteria andIdCampanaNotEqualTo(Integer value) {
			addCriterion("id_campana <>", value, "idCampana");
			return (Criteria) this;
		}

		public Criteria andIdCampanaGreaterThan(Integer value) {
			addCriterion("id_campana >", value, "idCampana");
			return (Criteria) this;
		}

		public Criteria andIdCampanaGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_campana >=", value, "idCampana");
			return (Criteria) this;
		}

		public Criteria andIdCampanaLessThan(Integer value) {
			addCriterion("id_campana <", value, "idCampana");
			return (Criteria) this;
		}

		public Criteria andIdCampanaLessThanOrEqualTo(Integer value) {
			addCriterion("id_campana <=", value, "idCampana");
			return (Criteria) this;
		}

		public Criteria andIdCampanaIn(List<Integer> values) {
			addCriterion("id_campana in", values, "idCampana");
			return (Criteria) this;
		}

		public Criteria andIdCampanaNotIn(List<Integer> values) {
			addCriterion("id_campana not in", values, "idCampana");
			return (Criteria) this;
		}

		public Criteria andIdCampanaBetween(Integer value1, Integer value2) {
			addCriterion("id_campana between", value1, value2, "idCampana");
			return (Criteria) this;
		}

		public Criteria andIdCampanaNotBetween(Integer value1, Integer value2) {
			addCriterion("id_campana not between", value1, value2, "idCampana");
			return (Criteria) this;
		}

		public Criteria andEstadoIsNull() {
			addCriterion("estado is null");
			return (Criteria) this;
		}

		public Criteria andEstadoIsNotNull() {
			addCriterion("estado is not null");
			return (Criteria) this;
		}

		public Criteria andEstadoEqualTo(String value) {
			addCriterion("estado =", value, "estado");
			return (Criteria) this;
		}

		public Criteria andEstadoNotEqualTo(String value) {
			addCriterion("estado <>", value, "estado");
			return (Criteria) this;
		}

		public Criteria andEstadoGreaterThan(String value) {
			addCriterion("estado >", value, "estado");
			return (Criteria) this;
		}

		public Criteria andEstadoGreaterThanOrEqualTo(String value) {
			addCriterion("estado >=", value, "estado");
			return (Criteria) this;
		}

		public Criteria andEstadoLessThan(String value) {
			addCriterion("estado <", value, "estado");
			return (Criteria) this;
		}

		public Criteria andEstadoLessThanOrEqualTo(String value) {
			addCriterion("estado <=", value, "estado");
			return (Criteria) this;
		}

		public Criteria andEstadoLike(String value) {
			addCriterion("estado like", value, "estado");
			return (Criteria) this;
		}

		public Criteria andEstadoNotLike(String value) {
			addCriterion("estado not like", value, "estado");
			return (Criteria) this;
		}

		public Criteria andEstadoIn(List<String> values) {
			addCriterion("estado in", values, "estado");
			return (Criteria) this;
		}

		public Criteria andEstadoNotIn(List<String> values) {
			addCriterion("estado not in", values, "estado");
			return (Criteria) this;
		}

		public Criteria andEstadoBetween(String value1, String value2) {
			addCriterion("estado between", value1, value2, "estado");
			return (Criteria) this;
		}

		public Criteria andEstadoNotBetween(String value1, String value2) {
			addCriterion("estado not between", value1, value2, "estado");
			return (Criteria) this;
		}

		public Criteria andFiabilidadIsNull() {
			addCriterion("fiabilidad is null");
			return (Criteria) this;
		}

		public Criteria andFiabilidadIsNotNull() {
			addCriterion("fiabilidad is not null");
			return (Criteria) this;
		}

		public Criteria andFiabilidadEqualTo(String value) {
			addCriterion("fiabilidad =", value, "fiabilidad");
			return (Criteria) this;
		}

		public Criteria andFiabilidadNotEqualTo(String value) {
			addCriterion("fiabilidad <>", value, "fiabilidad");
			return (Criteria) this;
		}

		public Criteria andFiabilidadGreaterThan(String value) {
			addCriterion("fiabilidad >", value, "fiabilidad");
			return (Criteria) this;
		}

		public Criteria andFiabilidadGreaterThanOrEqualTo(String value) {
			addCriterion("fiabilidad >=", value, "fiabilidad");
			return (Criteria) this;
		}

		public Criteria andFiabilidadLessThan(String value) {
			addCriterion("fiabilidad <", value, "fiabilidad");
			return (Criteria) this;
		}

		public Criteria andFiabilidadLessThanOrEqualTo(String value) {
			addCriterion("fiabilidad <=", value, "fiabilidad");
			return (Criteria) this;
		}

		public Criteria andFiabilidadLike(String value) {
			addCriterion("fiabilidad like", value, "fiabilidad");
			return (Criteria) this;
		}

		public Criteria andFiabilidadNotLike(String value) {
			addCriterion("fiabilidad not like", value, "fiabilidad");
			return (Criteria) this;
		}

		public Criteria andFiabilidadIn(List<String> values) {
			addCriterion("fiabilidad in", values, "fiabilidad");
			return (Criteria) this;
		}

		public Criteria andFiabilidadNotIn(List<String> values) {
			addCriterion("fiabilidad not in", values, "fiabilidad");
			return (Criteria) this;
		}

		public Criteria andFiabilidadBetween(String value1, String value2) {
			addCriterion("fiabilidad between", value1, value2, "fiabilidad");
			return (Criteria) this;
		}

		public Criteria andFiabilidadNotBetween(String value1, String value2) {
			addCriterion("fiabilidad not between", value1, value2, "fiabilidad");
			return (Criteria) this;
		}

		public Criteria andIdUsuarioIsNull() {
			addCriterion("id_usuario is null");
			return (Criteria) this;
		}

		public Criteria andIdUsuarioIsNotNull() {
			addCriterion("id_usuario is not null");
			return (Criteria) this;
		}

		public Criteria andIdUsuarioEqualTo(Integer value) {
			addCriterion("id_usuario =", value, "idUsuario");
			return (Criteria) this;
		}

		public Criteria andIdUsuarioNotEqualTo(Integer value) {
			addCriterion("id_usuario <>", value, "idUsuario");
			return (Criteria) this;
		}

		public Criteria andIdUsuarioGreaterThan(Integer value) {
			addCriterion("id_usuario >", value, "idUsuario");
			return (Criteria) this;
		}

		public Criteria andIdUsuarioGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_usuario >=", value, "idUsuario");
			return (Criteria) this;
		}

		public Criteria andIdUsuarioLessThan(Integer value) {
			addCriterion("id_usuario <", value, "idUsuario");
			return (Criteria) this;
		}

		public Criteria andIdUsuarioLessThanOrEqualTo(Integer value) {
			addCriterion("id_usuario <=", value, "idUsuario");
			return (Criteria) this;
		}

		public Criteria andIdUsuarioIn(List<Integer> values) {
			addCriterion("id_usuario in", values, "idUsuario");
			return (Criteria) this;
		}

		public Criteria andIdUsuarioNotIn(List<Integer> values) {
			addCriterion("id_usuario not in", values, "idUsuario");
			return (Criteria) this;
		}

		public Criteria andIdUsuarioBetween(Integer value1, Integer value2) {
			addCriterion("id_usuario between", value1, value2, "idUsuario");
			return (Criteria) this;
		}

		public Criteria andIdUsuarioNotBetween(Integer value1, Integer value2) {
			addCriterion("id_usuario not between", value1, value2, "idUsuario");
			return (Criteria) this;
		}

		public Criteria andIdUsuarioApoyoIsNull() {
			addCriterion("id_usuario_apoyo is null");
			return (Criteria) this;
		}

		public Criteria andIdUsuarioApoyoIsNotNull() {
			addCriterion("id_usuario_apoyo is not null");
			return (Criteria) this;
		}

		public Criteria andIdUsuarioApoyoEqualTo(Integer value) {
			addCriterion("id_usuario_apoyo =", value, "idUsuarioApoyo");
			return (Criteria) this;
		}

		public Criteria andIdUsuarioApoyoNotEqualTo(Integer value) {
			addCriterion("id_usuario_apoyo <>", value, "idUsuarioApoyo");
			return (Criteria) this;
		}

		public Criteria andIdUsuarioApoyoGreaterThan(Integer value) {
			addCriterion("id_usuario_apoyo >", value, "idUsuarioApoyo");
			return (Criteria) this;
		}

		public Criteria andIdUsuarioApoyoGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_usuario_apoyo >=", value, "idUsuarioApoyo");
			return (Criteria) this;
		}

		public Criteria andIdUsuarioApoyoLessThan(Integer value) {
			addCriterion("id_usuario_apoyo <", value, "idUsuarioApoyo");
			return (Criteria) this;
		}

		public Criteria andIdUsuarioApoyoLessThanOrEqualTo(Integer value) {
			addCriterion("id_usuario_apoyo <=", value, "idUsuarioApoyo");
			return (Criteria) this;
		}

		public Criteria andIdUsuarioApoyoIn(List<Integer> values) {
			addCriterion("id_usuario_apoyo in", values, "idUsuarioApoyo");
			return (Criteria) this;
		}

		public Criteria andIdUsuarioApoyoNotIn(List<Integer> values) {
			addCriterion("id_usuario_apoyo not in", values, "idUsuarioApoyo");
			return (Criteria) this;
		}

		public Criteria andIdUsuarioApoyoBetween(Integer value1, Integer value2) {
			addCriterion("id_usuario_apoyo between", value1, value2,
					"idUsuarioApoyo");
			return (Criteria) this;
		}

		public Criteria andIdUsuarioApoyoNotBetween(Integer value1,
				Integer value2) {
			addCriterion("id_usuario_apoyo not between", value1, value2,
					"idUsuarioApoyo");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table public.observacion
	 * 
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table observacion
	 * 
	 * @mbggenerated do_not_delete_during_merge Sat Jun 04 08:05:19 ART 2011
	 */
	public static class Criteria extends GeneratedCriteria {

		protected Criteria() {
			super();
		}
	}
}