package ar.edu.unicen.exa.galvarez.patogis.servidor.modelo;

import java.io.Serializable;

public class ObservacionEspecie implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = -3955657492269272900L;

	public ObservacionEspecie() {
		// TODO Auto-generated constructor stub
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column public.observacion_especie.id
	 * 
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column public.observacion_especie.cantidad
	 * 
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	private Integer cantidad;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column public.observacion_especie.distancia
	 * 
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	private String distancia;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column public.observacion_especie.conteo
	 * 
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	private String conteo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column public.observacion_especie.edad
	 * 
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	private String edad;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column public.observacion_especie.observaciones
	 * 
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	private String observaciones;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column public.observacion_especie.id_observacion
	 * 
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	private Integer idObservacion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column public.observacion_especie.id_especie
	 * 
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	private Integer idEspecie;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column public.observacion_especie.id
	 * 
	 * @return the value of public.observacion_especie.id
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column public.observacion_especie.id
	 * 
	 * @param id
	 *            the value for public.observacion_especie.id
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column public.observacion_especie.cantidad
	 * 
	 * @return the value of public.observacion_especie.cantidad
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public Integer getCantidad() {
		return cantidad;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column public.observacion_especie.cantidad
	 * 
	 * @param cantidad
	 *            the value for public.observacion_especie.cantidad
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column public.observacion_especie.distancia
	 * 
	 * @return the value of public.observacion_especie.distancia
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public String getDistancia() {
		return distancia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column public.observacion_especie.distancia
	 * 
	 * @param distancia
	 *            the value for public.observacion_especie.distancia
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public void setDistancia(String distancia) {
		this.distancia = distancia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column public.observacion_especie.conteo
	 * 
	 * @return the value of public.observacion_especie.conteo
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public String getConteo() {
		return conteo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column public.observacion_especie.conteo
	 * 
	 * @param conteo
	 *            the value for public.observacion_especie.conteo
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public void setConteo(String conteo) {
		this.conteo = conteo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column public.observacion_especie.edad
	 * 
	 * @return the value of public.observacion_especie.edad
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public String getEdad() {
		return edad;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column public.observacion_especie.edad
	 * 
	 * @param edad
	 *            the value for public.observacion_especie.edad
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public void setEdad(String edad) {
		this.edad = edad;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column public.observacion_especie.observaciones
	 * 
	 * @return the value of public.observacion_especie.observaciones
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public String getObservaciones() {
		return observaciones;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column public.observacion_especie.observaciones
	 * 
	 * @param observaciones
	 *            the value for public.observacion_especie.observaciones
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column public.observacion_especie.id_observacion
	 * 
	 * @return the value of public.observacion_especie.id_observacion
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public Integer getIdObservacion() {
		return idObservacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column public.observacion_especie.id_observacion
	 * 
	 * @param idObservacion
	 *            the value for public.observacion_especie.id_observacion
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public void setIdObservacion(Integer idObservacion) {
		this.idObservacion = idObservacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column public.observacion_especie.id_especie
	 * 
	 * @return the value of public.observacion_especie.id_especie
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public Integer getIdEspecie() {
		return idEspecie;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column public.observacion_especie.id_especie
	 * 
	 * @param idEspecie
	 *            the value for public.observacion_especie.id_especie
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public void setIdEspecie(Integer idEspecie) {
		this.idEspecie = idEspecie;
	}
}