package ar.edu.unicen.exa.galvarez.patogis.servidor.modelo;

import java.util.Date;

public class Observacion {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.observacion.id
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.observacion.inicio
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	private Date inicio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.observacion.fin
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	private Date fin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.observacion.alcance
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	private String alcance;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.observacion.observaciones
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	private String observaciones;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.observacion.id_ubicacion
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	private Integer idUbicacion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.observacion.id_campana
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	private Integer idCampana;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.observacion.estado
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	private String estado;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.observacion.fiabilidad
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	private String fiabilidad;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.observacion.id_usuario
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	private Integer idUsuario;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.observacion.id_usuario_apoyo
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	private Integer idUsuarioApoyo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.observacion.id
	 * @return  the value of public.observacion.id
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.observacion.id
	 * @param id  the value for public.observacion.id
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.observacion.inicio
	 * @return  the value of public.observacion.inicio
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	public Date getInicio() {
		return inicio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.observacion.inicio
	 * @param inicio  the value for public.observacion.inicio
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	public void setInicio(Date inicio) {
		this.inicio = inicio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.observacion.fin
	 * @return  the value of public.observacion.fin
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	public Date getFin() {
		return fin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.observacion.fin
	 * @param fin  the value for public.observacion.fin
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	public void setFin(Date fin) {
		this.fin = fin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.observacion.alcance
	 * @return  the value of public.observacion.alcance
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	public String getAlcance() {
		return alcance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.observacion.alcance
	 * @param alcance  the value for public.observacion.alcance
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	public void setAlcance(String alcance) {
		this.alcance = alcance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.observacion.observaciones
	 * @return  the value of public.observacion.observaciones
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	public String getObservaciones() {
		return observaciones;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.observacion.observaciones
	 * @param observaciones  the value for public.observacion.observaciones
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.observacion.id_ubicacion
	 * @return  the value of public.observacion.id_ubicacion
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	public Integer getIdUbicacion() {
		return idUbicacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.observacion.id_ubicacion
	 * @param idUbicacion  the value for public.observacion.id_ubicacion
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	public void setIdUbicacion(Integer idUbicacion) {
		this.idUbicacion = idUbicacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.observacion.id_campana
	 * @return  the value of public.observacion.id_campana
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	public Integer getIdCampana() {
		return idCampana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.observacion.id_campana
	 * @param idCampana  the value for public.observacion.id_campana
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	public void setIdCampana(Integer idCampana) {
		this.idCampana = idCampana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.observacion.estado
	 * @return  the value of public.observacion.estado
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	public String getEstado() {
		return estado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.observacion.estado
	 * @param estado  the value for public.observacion.estado
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	public void setEstado(String estado) {
		this.estado = estado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.observacion.fiabilidad
	 * @return  the value of public.observacion.fiabilidad
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	public String getFiabilidad() {
		return fiabilidad;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.observacion.fiabilidad
	 * @param fiabilidad  the value for public.observacion.fiabilidad
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	public void setFiabilidad(String fiabilidad) {
		this.fiabilidad = fiabilidad;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.observacion.id_usuario
	 * @return  the value of public.observacion.id_usuario
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	public Integer getIdUsuario() {
		return idUsuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.observacion.id_usuario
	 * @param idUsuario  the value for public.observacion.id_usuario
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.observacion.id_usuario_apoyo
	 * @return  the value of public.observacion.id_usuario_apoyo
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	public Integer getIdUsuarioApoyo() {
		return idUsuarioApoyo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.observacion.id_usuario_apoyo
	 * @param idUsuarioApoyo  the value for public.observacion.id_usuario_apoyo
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	public void setIdUsuarioApoyo(Integer idUsuarioApoyo) {
		this.idUsuarioApoyo = idUsuarioApoyo;
	}
}