package ar.edu.unicen.exa.galvarez.patogis.servidor.modelo;

import java.util.ArrayList;
import java.util.List;
import java.util.Date;

public class ObservacionFotoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.observacion_foto
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.observacion_foto
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.observacion_foto
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_foto
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	public ObservacionFotoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_foto
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_foto
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_foto
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_foto
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_foto
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_foto
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_foto
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_foto
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_foto
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.observacion_foto
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table public.observacion_foto
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andNombreArchivoIsNull() {
			addCriterion("nombre_archivo is null");
			return (Criteria) this;
		}

		public Criteria andNombreArchivoIsNotNull() {
			addCriterion("nombre_archivo is not null");
			return (Criteria) this;
		}

		public Criteria andNombreArchivoEqualTo(String value) {
			addCriterion("nombre_archivo =", value, "nombreArchivo");
			return (Criteria) this;
		}

		public Criteria andNombreArchivoNotEqualTo(String value) {
			addCriterion("nombre_archivo <>", value, "nombreArchivo");
			return (Criteria) this;
		}

		public Criteria andNombreArchivoGreaterThan(String value) {
			addCriterion("nombre_archivo >", value, "nombreArchivo");
			return (Criteria) this;
		}

		public Criteria andNombreArchivoGreaterThanOrEqualTo(String value) {
			addCriterion("nombre_archivo >=", value, "nombreArchivo");
			return (Criteria) this;
		}

		public Criteria andNombreArchivoLessThan(String value) {
			addCriterion("nombre_archivo <", value, "nombreArchivo");
			return (Criteria) this;
		}

		public Criteria andNombreArchivoLessThanOrEqualTo(String value) {
			addCriterion("nombre_archivo <=", value, "nombreArchivo");
			return (Criteria) this;
		}

		public Criteria andNombreArchivoLike(String value) {
			addCriterion("nombre_archivo like", value, "nombreArchivo");
			return (Criteria) this;
		}

		public Criteria andNombreArchivoNotLike(String value) {
			addCriterion("nombre_archivo not like", value, "nombreArchivo");
			return (Criteria) this;
		}

		public Criteria andNombreArchivoIn(List<String> values) {
			addCriterion("nombre_archivo in", values, "nombreArchivo");
			return (Criteria) this;
		}

		public Criteria andNombreArchivoNotIn(List<String> values) {
			addCriterion("nombre_archivo not in", values, "nombreArchivo");
			return (Criteria) this;
		}

		public Criteria andNombreArchivoBetween(String value1, String value2) {
			addCriterion("nombre_archivo between", value1, value2,
					"nombreArchivo");
			return (Criteria) this;
		}

		public Criteria andNombreArchivoNotBetween(String value1, String value2) {
			addCriterion("nombre_archivo not between", value1, value2,
					"nombreArchivo");
			return (Criteria) this;
		}

		public Criteria andTipoIsNull() {
			addCriterion("tipo is null");
			return (Criteria) this;
		}

		public Criteria andTipoIsNotNull() {
			addCriterion("tipo is not null");
			return (Criteria) this;
		}

		public Criteria andTipoEqualTo(String value) {
			addCriterion("tipo =", value, "tipo");
			return (Criteria) this;
		}

		public Criteria andTipoNotEqualTo(String value) {
			addCriterion("tipo <>", value, "tipo");
			return (Criteria) this;
		}

		public Criteria andTipoGreaterThan(String value) {
			addCriterion("tipo >", value, "tipo");
			return (Criteria) this;
		}

		public Criteria andTipoGreaterThanOrEqualTo(String value) {
			addCriterion("tipo >=", value, "tipo");
			return (Criteria) this;
		}

		public Criteria andTipoLessThan(String value) {
			addCriterion("tipo <", value, "tipo");
			return (Criteria) this;
		}

		public Criteria andTipoLessThanOrEqualTo(String value) {
			addCriterion("tipo <=", value, "tipo");
			return (Criteria) this;
		}

		public Criteria andTipoLike(String value) {
			addCriterion("tipo like", value, "tipo");
			return (Criteria) this;
		}

		public Criteria andTipoNotLike(String value) {
			addCriterion("tipo not like", value, "tipo");
			return (Criteria) this;
		}

		public Criteria andTipoIn(List<String> values) {
			addCriterion("tipo in", values, "tipo");
			return (Criteria) this;
		}

		public Criteria andTipoNotIn(List<String> values) {
			addCriterion("tipo not in", values, "tipo");
			return (Criteria) this;
		}

		public Criteria andTipoBetween(String value1, String value2) {
			addCriterion("tipo between", value1, value2, "tipo");
			return (Criteria) this;
		}

		public Criteria andTipoNotBetween(String value1, String value2) {
			addCriterion("tipo not between", value1, value2, "tipo");
			return (Criteria) this;
		}

		public Criteria andIdObservacionIsNull() {
			addCriterion("id_observacion is null");
			return (Criteria) this;
		}

		public Criteria andIdObservacionIsNotNull() {
			addCriterion("id_observacion is not null");
			return (Criteria) this;
		}

		public Criteria andIdObservacionEqualTo(Integer value) {
			addCriterion("id_observacion =", value, "idObservacion");
			return (Criteria) this;
		}

		public Criteria andIdObservacionNotEqualTo(Integer value) {
			addCriterion("id_observacion <>", value, "idObservacion");
			return (Criteria) this;
		}

		public Criteria andIdObservacionGreaterThan(Integer value) {
			addCriterion("id_observacion >", value, "idObservacion");
			return (Criteria) this;
		}

		public Criteria andIdObservacionGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_observacion >=", value, "idObservacion");
			return (Criteria) this;
		}

		public Criteria andIdObservacionLessThan(Integer value) {
			addCriterion("id_observacion <", value, "idObservacion");
			return (Criteria) this;
		}

		public Criteria andIdObservacionLessThanOrEqualTo(Integer value) {
			addCriterion("id_observacion <=", value, "idObservacion");
			return (Criteria) this;
		}

		public Criteria andIdObservacionIn(List<Integer> values) {
			addCriterion("id_observacion in", values, "idObservacion");
			return (Criteria) this;
		}

		public Criteria andIdObservacionNotIn(List<Integer> values) {
			addCriterion("id_observacion not in", values, "idObservacion");
			return (Criteria) this;
		}

		public Criteria andIdObservacionBetween(Integer value1, Integer value2) {
			addCriterion("id_observacion between", value1, value2,
					"idObservacion");
			return (Criteria) this;
		}

		public Criteria andIdObservacionNotBetween(Integer value1,
				Integer value2) {
			addCriterion("id_observacion not between", value1, value2,
					"idObservacion");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table public.observacion_foto
	 * @mbggenerated  Sun Jun 12 16:42:33 ART 2011
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table observacion_foto
     *
     * @mbggenerated do_not_delete_during_merge Sat Jun 04 08:05:19 ART 2011
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}