package ar.edu.unicen.exa.galvarez.patogis.servidor.modelo;

import java.io.Serializable;

public class ParUsuarios implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = -6502323881385230207L;

	public ParUsuarios() {
		// TODO Auto-generated constructor stub
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column public.par_usuarios.id
	 * 
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column public.par_usuarios.id_usuario
	 * 
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	private Integer idUsuario;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column public.par_usuarios.id_usuario_apoyo
	 * 
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	private Integer idUsuarioApoyo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column public.par_usuarios.tipo
	 * 
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	private String tipo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column public.par_usuarios.id_campana
	 * 
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	private Integer idCampana;

	private Usuario usuario;
	private Usuario usuarioApoyo;
	private Campana campana;

	public Usuario getUsuario() {
		return usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Usuario getUsuarioApoyo() {
		return usuarioApoyo;
	}

	public void setUsuarioApoyo(Usuario usuarioApoyo) {
		this.usuarioApoyo = usuarioApoyo;
	}

	public Campana getCampana() {
		return campana;
	}

	public void setCampana(Campana campana) {
		this.campana = campana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column public.par_usuarios.id
	 * 
	 * @return the value of public.par_usuarios.id
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column public.par_usuarios.id
	 * 
	 * @param id
	 *            the value for public.par_usuarios.id
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column public.par_usuarios.id_usuario
	 * 
	 * @return the value of public.par_usuarios.id_usuario
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public Integer getIdUsuario() {
		return idUsuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column public.par_usuarios.id_usuario
	 * 
	 * @param idUsuario
	 *            the value for public.par_usuarios.id_usuario
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column public.par_usuarios.id_usuario_apoyo
	 * 
	 * @return the value of public.par_usuarios.id_usuario_apoyo
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public Integer getIdUsuarioApoyo() {
		return idUsuarioApoyo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column public.par_usuarios.id_usuario_apoyo
	 * 
	 * @param idUsuarioApoyo
	 *            the value for public.par_usuarios.id_usuario_apoyo
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public void setIdUsuarioApoyo(Integer idUsuarioApoyo) {
		this.idUsuarioApoyo = idUsuarioApoyo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column public.par_usuarios.tipo
	 * 
	 * @return the value of public.par_usuarios.tipo
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public String getTipo() {
		return tipo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column public.par_usuarios.tipo
	 * 
	 * @param tipo
	 *            the value for public.par_usuarios.tipo
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column public.par_usuarios.id_campana
	 * 
	 * @return the value of public.par_usuarios.id_campana
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public Integer getIdCampana() {
		return idCampana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column public.par_usuarios.id_campana
	 * 
	 * @param idCampana
	 *            the value for public.par_usuarios.id_campana
	 * @mbggenerated Sun Jun 12 16:42:33 ART 2011
	 */
	public void setIdCampana(Integer idCampana) {
		this.idCampana = idCampana;
	}
}